import { Geist, Geist_Mono } from "next/font/google";

import ClientProvider from "@/redux/store/ClientProvider"
import ClientWrapper from "@/redux/store/ClientWrapper"

import "./globals.css"
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from "react-toastify"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ToastContainer position='top-right'/>
                <ClientProvider>
                    <ClientWrapper>
                        {children}
                    </ClientWrapper>
                </ClientProvider>
            </body>
        </html>
    );
}  